
name: Update Kintone Records

on:
  schedule:
    - cron: '0 16 * * *'  # JST 1:00AM（UTC換算）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        env:
          KINTONE_DOMAIN: ${{ secrets.KINTONE_DOMAIN }}
          KINTONE_API_TOKEN: ${{ secrets.KINTONE_API_TOKEN }}
          KINTONE_APP_ID: ${{ secrets.KINTONE_APP_ID }}
          KINTONE_BASIC_USER: ${{ secrets.KINTONE_BASIC_USER }}
          KINTONE_BASIC_PASS: ${{ secrets.KINTONE_BASIC_PASS }}
        run: node update.js
